# Generated by Django 5.1.2 on 2024-10-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='file',
            new_name='file_path',
        ),
    ]
